# Generated by Django 4.2 on 2025-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_stripe_payment_intent_id_order_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chefprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
