# Generated by Django 4.2 on 2025-11-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251106_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='chefprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='chefprofile',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='chefprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
